### ISSUE TITLE
defining STUN server

### ISSUE THREAD

**Issue by hrshovon** [dkumor/rtcbot#7]
Hello,
I am trying to write two different python scripts. Each of which would run in separate networks(one might be in cloud platform with no real ip, another might be behind a home router with no real ip).

I want to know how to exchange connection parameters in such a case.
I modified the code written here(https://rtcbot.readthedocs.io/en/latest/examples/mobile/README.html)
 to my needs and had to write my own very simple STUN server.

`
#Video transmission
import asyncio
import aiohttp
import cv2
import json
from rtcbot import RTCConnection, Gamepad, CVDisplay
import random
import dlib
import threading
disp = CVDisplay()
resized=None
#g = Gamepad()
conn = RTCConnection()
detector = dlib.get_frontal_face_detector()

async def process_and_run():
    global resized
    while True:
    	await asyncio.sleep(0.05)
    	if resized is not None:
                dets=detector(resized,0)
                for i,d in enumerate(dets):
                    cv2.rectangle(resized,(d.left(),d.top()),(d.right(),d.bottom()),(0,255,0))
                disp.put_nowait(resized)
    
@conn.video.subscribe
def onFrame(frame):
    global resized
    resized = cv2.resize(frame, (frame.shape[1] * 4, frame.shape[0] * 4))
    conn.put_nowait({"data": random.random()})

async def connect():
    localDescription = await conn.getLocalDescription()
    async with aiohttp.ClientSession() as session:
        async with session.post(
            "http://<some_ip>:8080/connect_server", data=json.dumps(localDescription)
        ) as resp:
            response = await resp.json()
            await conn.setRemoteDescription(response)
    

asyncio.ensure_future(connect())
asyncio.ensure_future(process_and_run())
try:
    loop = asyncio.get_event_loop()
    loop.run_forever()
finally:
    conn.close()
    disp.close()
    
`

Code for Video reception
`
import asyncio
import aiohttp
import json
from aiohttp import web
routes = web.RouteTableDef()

from rtcbot import RTCConnection, CVCamera
cam = CVCamera(cameranumber=1)
conn = RTCConnection()
conn.video.putSubscription(cam)

@conn.subscribe
def controls(msg):
    print("Control message:", msg)

async def connect():
    clo=None
    async with aiohttp.ClientSession() as session:
        async with session.post("http://192.168.100.101:8080/req_client") as resp:
            clo = await conn.getLocalDescription(await resp.json())
            print(clo)
        async with session.post("http://<some_ip>:8080/connect_client", data=json.dumps(clo)) as resp:
            response = await resp.json()
            #await conn.setRemoteDescription(response)
    # Start sending gamepad controls
    #g.subscribe(conn)
    print("okay")	
async def cleanup(app):
    await conn.close()
    cam.close()

asyncio.ensure_future(connect())
try:
    asyncio.get_event_loop().run_forever()
finally:
    cleanup()

`

and the laughable STUN server at <some_ip>
`
import asyncio
from aiohttp import web
routes = web.RouteTableDef()

cl_data=None
srv_data=None

async def get_cl():
    while cl_data is None:
        pass
    return cl_data

async def get_srv():
    while srv_data is None:
        pass
    return srv_data

@routes.post("/req_client")
async def connect_req(request):
    global cl_data
    global srv_data
    print("got it")
    return web.json_response(srv_data)

@routes.post("/connect_client")
async def connect_cl(request):
    global cl_data
    global srv_data
    clientOffer = await request.json()
    cl_data = clientOffer
    print(cl_data)
    await asyncio.sleep(10)
    return web.json_response(srv_data)

@routes.post("/connect_server")
async def connect_srv(request):
    global cl_data
    global srv_data
    clientOffer = await request.json()
    srv_data = clientOffer
    print(srv_data)
    await asyncio.sleep(10)
    return web.json_response(cl_data)

app = web.Application()
app.add_routes(routes)
web.run_app(app)
`

But at the end of the 4G tutorial, you mentioned

> myConnection = RTCConnection(rtcConfiguration=RTCConfiguration([
                    RTCIceServer(urls="stun:stun.l.google.com:19302"),
                    RTCIceServer(urls="turn:my.server.ip:3478",
                        username="myusername",credential="mypassword")
                ]))

Here, I see that a STUN server has been defined. In this case, how to write the connect function for each script?

**Comment by dkumor** [comment]
In general, you don't need to modify the `rtcConfiguration`. The google stun server is totally fine for most cases - all a STUN server does is give the script its current internet-facing IP address (ie, the script only knows that it is at `192.168.100.10` on your local network, it doesn't know what its IP address is on the internet, and that's what a STUN server is for) - it does not really help in establishing a connection.

To the best of my understanding, the question here is how to exchange connection parameters when neither party knows the other's IP address. This is generally a difficult problem, since they have to communicate *somehow*.

The solution used in the tutorial is that of a separate internet-accessible mini python server that serves as a go-between. That is, the connection parameters go as follows:
```
device 1 <-> mini server <-> device 2
```
Device 1 and 2 know the IP address of the mini server, so they can connect to it, and the server passes connection parameters from one device to the other. The server is no longer needed after the connection is established.

You will notice in the tutorial that Device1 is the "Remote Code", the mini server is "Server", and Device 2 is actually the browser which is running the code served at `index`.

The only difficulty here is the the "mini server" needs to be at a known IP address (or known domain name). This means that you need to either use a virtual machine from a provider like AWS or DigitalOcean, or you can run the mini server on a computer you own, but "port forward" it to the internet. 

Once the mini server is at a known location, it doesn't matter where Device 1 and Device 2 are - so long as they can use the mini server to forward their messages to each other.

As a side note, I am thinking that maybe it might be a good idea to offer a "mini server" on my own machine, so that people can try it out without going through the complexity of setting one up on the internet. I will look into it this weekend.

I hope that helped with your question!

**Comment by dkumor** [comment]
Actually, after looking at your code in more detail, it looks OK - the server you have looks like a working mini server. If it doesn't work for you, you might need a `TURN` server - which is something else entirely.

Try it first without defining any rtcConfiguration - it should work fine in most cases!

**Comment by dkumor** [comment]
I have created a free public connection server at https://rtcbot.dev, and added it to the documentation.
See: https://rtcbot.readthedocs.io/en/latest/examples/mobile/README.html#rtcbot-dev

Hope it helps!

**Comment by dkumor** [comment]
I am closing this issue - please reopen if it is still relevant.
